#!/bin/bash
PROJECT_DIR="$(dirname "$0")"
python3 -m venv $PROJECT_DIR/../.venv
source $PROJECT_DIR/../.venv/bin/activate
pip install --requirement $PROJECT_DIR/../api/requirements.txt

source ./mongodb_setup