#!/bin/bash

while getopts ":l:p:s:d:" opt; do
  case $opt in
    l) login="$OPTARG"
    ;;
    p) pwd="$OPTARG"
    ;;
    s) sheets="$OPTARG"
    ;;
    d) docs="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done

PROJECT_DIR="$(dirname "$0")"
python3 -m venv $PROJECT_DIR/../.venv
source $PROJECT_DIR/../.venv/bin/activate
pip install --requirement $PROJECT_DIR/../api/requirements.txt

bash $PROJECT_DIR/mongodb_setup.sh

bash $PROJECT_DIR/init_ini.sh -l "$login" -p "$pwd" -s "$sheets" -d "$docs"